name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROTOC_VERSION: 22.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Static analysis
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings